spring.application.name=CUSTOMER-SERVICE
server.port = 9091
spring.datasource.url=jdbc:postgresql://localhost:5432/customers
spring.datasource.username=postgres
spring.datasource.password=corp@123
spring.jpa.hibernate.ddl-auto=update
spring.cloud.openfeign.circuitbreaker.enabled=true
logging.level.root=INFO



#eureka.instance.prefer-ip-address=true
#eureka.instance.hostname=localhost
#eureka.instance.ip-address=127.0.0.1
#eureka.instance.instance-id=${spring.application.name}:${server.port}


# Eureka
logging.level.com.netflix.discovery=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG

# Load Balancer (Feign uses this)
logging.level.org.springframework.cloud.loadbalancer=DEBUG

# Feign clients
logging.level.org.springframework.cloud.openfeign=DEBUG

huggingface.api.key=${HUGGINGFACE_API_KEY}

spring.ai.openai.base-url=https://router.huggingface.co

spring.ai.openai.chat.options.model=meta-llama/Llama-3.1-8B-Instruct

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=TRACE
logging.level.org.springframework.web=DEBUG

#spring.ai.openai.api-key=gsk_xxxxx
#spring.ai.openai.base-url=https://api.groq.com/openai
#spring.ai.openai.chat.options.model=llama-3.1-8b-instant
